env:
  browser: true
  commonjs: true
  es6: true
extends: 'gaea'
plugins:
 - html
globals:
  define: true
  $: true
rules:
  max-depth:
    - "error"
    -
      "max": 7
  id-length:
    - "error"
    -
      "max": 34
      "min": 1
  no-magic-numbers:
    - "error"
    -
      "ignore":
        - -2
        - -1
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9