env:
  browser: true
  commonjs: true
  es6: true
extends: 'gaea'
plugins:
 - html
globals:
  define: true
  $: true
rules:
  max-depth:
    - "error"
    -
      "max": 7
  id-length:
    - "error"
    -
      "max": 34
      "min": 1