# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  install:
    docker:
      - image: circleci/node:8.7-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node_modules-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v2-node_modules-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint:
    docker:
      - image: circleci/node:8.7-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node_modules-{{ checksum "package.json" }}
      - run: npm run lint
  build:
    docker:
      - image: circleci/node:8.7-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node_modules-{{ checksum "package.json" }}
      - run: npm run build
      - save_cache:
          key: v2-build
          paths:
            - dist
            - docs
  test-unit:
    docker:
      - image: circleci/node:8.7-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node_modules-{{ checksum "package.json" }}
            - v2-build-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm run unit
  test-e2e:
    docker:
      - image: circleci/node:8.7-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node_modules-{{ checksum "package.json" }}
            - v2-build-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm run doc -- --port 8089 & npm run e2e
  coverage:
    docker:
      - image: circleci/node:8.7-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node_modules-{{ checksum "package.json" }}
            - v2-build-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm run doc -- --port 8089 & npm run cover

workflows:
  version: 2
  lint_and_test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
      - test-unit:
          requires:
            - build
      - test-e2e:
          requires:
            - build
      - coverage:
          requires:
            - test-unit
            - test-e2e